apiVersion: v1
kind: Service
metadata:
  name: client-frontend-service
spec:
  selector:
    app: frontend
    type: frontend-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 1102
      targetPort: 1102
      nodePort: 31364
