apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211102-backend-classroom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i211102-classroom-backend
  template:
    metadata:
      labels:
        app: i211102-classroom-backend
    spec: 
      containers:
      - name: i211102-classroom-backend
        image: ibraheem15/classroom:latest
        ports:
        - containerPort: 3103
        env:
        - name: PORT
          value: "3103"