apiVersion: v1
kind: Service
metadata:
  name: 1102-classroom-backend-service
spec:
  selector:
    app: 1102-classroom-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3103
      nodePort: 30000
  type: NodePort