apiVersion: v1
kind: Service
metadata:
  name: i211102-event-bus-backend-service
spec:
  selector:
    app: i321102-event-bus-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3109
  type: NodePort