apiVersion: v1
kind: Service
metadata:
  name: 1102-event-bus-backend-service
spec:
  selector:
    app: 1102-event-bus-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3109
      nodePort: 30000
  type: NodePort