apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1102-backend-event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1102-event-bus-backend
  template:
    metadata:
      labels:
        app: 1102-event-bus-backend
    spec:
      containers:
      - name: 1102-event-bus-backend
        image: ibraheem15/event-bus:latest
        ports:
        - containerPort: 3109
        env:
        - name: PORT
          value: "3109"