apiVersion: v1
kind: Service
metadata:
  name: 1102-auth-backend-service
spec:
  selector:
    app: 1102-auth-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3102
      nodePort: 30000
  type: NodePort