apiVersion: v1
kind: Service
metadata:
  name: i211102-post-backend-service
spec:
  selector:
    app: i211102-post-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3102
  type: NodePort