apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1102-backend-post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1102-post-backend
  template:
    metadata:
      labels:
        app: 1102-post-backend
    spec:
      containers:
      - name: 1102-post-backend
        image: ibraheem15/post:latest
        ports:
        - containerPort: 3102
        env:
        - name: PORT
          value: "3102"